name: Build & Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2.1.2

    - name: Install packages
      run: yarn
    - name: Build
      run: yarn build
    - name: Set port
      run: export PORT=${{ secrets.PORT }}
    - name: Serve
      run: serve ./build
